package com.example.amistapp.Parametros

object Rutas {
    val login = "login"
    var administrador = "administrador"
    var estandar = "estandar"
    var perfil = "perfil"
    var noActivado = "noActivado"
    var altaUsuario = "altaUsuario"
    var bajaUsuarios = "bajaUsuarios"
    var activarDesActivar = "activarDesactivar"
    var cambiarRole = "cambiarRole"
    var mapa = "mapa"
    var crearEvento = "crearEvento"
    var proximosEventos = "proximosEventos"
    var historialEventos = "historialEventos"
    var eventosDisponibles = "eventosDisponibles"
    var misEventos = "misEventos"
    var bodyVentanaEstandarEventos ="bodyVentanaEstandarEventos"
    var bodyVentanaAdminEventos = "bodyVentanaAdminEventos"
    var bodyVentanaAdminUsuarios = "bodyVentanaAdminUsuarios"
    var mostrarInscritos = "mostrarInscritos"
    var mapaUbicacionUsuario = "mapaUbicacionUsuario"
    var mostrarAsistentes = "mostrarAsistentes"
}